-- ═══════════════════════════════════════════════════════════
-- Migración S5-04: Seed de medicamentos para todos los doctores
-- ═══════════════════════════════════════════════════════════
-- Inserta 736 medicamentos como base inicial del catálogo
-- de cada doctor existente en la tabla `doctors`.
--
-- Características:
--   - Dedupe case-insensitive por (doctor_id, commercial_name + concentration)
--     para no duplicar el mismo medicamento en distintas concentraciones.
--   - is_active=true, usage_count=0 por default.
--   - Mapeo de presentación documentado en s5_02_extend_medication_presentation.sql
--
-- IMPORTANTE: ejecutar PRIMERO s5_02_extend_medication_presentation.sql
-- para que el enum tenga 'sobre' y 'gel'.
--
-- Idempotente: se puede correr varias veces sin duplicar datos.
-- ═══════════════════════════════════════════════════════════

INSERT INTO medications (doctor_id, commercial_name, active_ingredient, concentration, presentation, is_active, usage_count)
SELECT d.id, x.commercial_name, x.active_ingredient, x.concentration, x.presentation, true, 0
FROM doctors d
CROSS JOIN (VALUES
  ('Adimet XR', 'Metformina', '1000 mg', 'tableta'::medication_presentation),
  ('Albisec One', 'Itraconazol + Secnidazol', '133 mg + 666 mg', 'tableta'::medication_presentation),
  ('Albisec One', 'Itraconazol + Secnidazol', '133.33 mg', 'tableta'::medication_presentation),
  ('Aldactone', 'Espironolactona', '100 mg', 'tableta'::medication_presentation),
  ('Aldactone', 'Espironolactona', '25 mg', 'tableta'::medication_presentation),
  ('Aldactone', 'Espironolactona', '50 mg', 'tableta'::medication_presentation),
  ('Alopurinol', 'Alopurinol', '300 mg', 'tableta'::medication_presentation),
  ('Altotab', 'Lercanidipino', '20 mg', 'tableta'::medication_presentation),
  ('Altrulin', 'Sertralina', '50 mg', 'tableta'::medication_presentation),
  ('Alutrin', 'Sertralina', '50 mg', 'tableta'::medication_presentation),
  ('Amaryl', 'Glimepirida', '2 mg', 'tableta'::medication_presentation),
  ('Amaryl', 'Glimepirida', '4 mg', 'tableta'::medication_presentation),
  ('Amiodarona', 'Amiodarona', '200 mg', 'tableta'::medication_presentation),
  ('Amiride', 'Glimepirida', '1 mg', 'tableta'::medication_presentation),
  ('Amiride', 'Glimepirida', '2 mg', 'tableta'::medication_presentation),
  ('Amiride', 'Glimepirida', '4 mg', 'tableta'::medication_presentation),
  ('Amitral', 'Amitriptilina', '25 mg', 'tableta'::medication_presentation),
  ('Amitriptilina', 'Amitriptilina', '25 mg', 'tableta'::medication_presentation),
  ('Amlodipina', 'Amlodipina', '10 mg', 'tableta'::medication_presentation),
  ('Amlodipina', 'Amlodipina', '5 mg', 'tableta'::medication_presentation),
  ('Amoxicilina', 'Amoxicilina', '500 mg', 'capsula'::medication_presentation),
  ('Analip', 'Atorvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Anfibol', 'Nebivolol', '5 mg', 'tableta'::medication_presentation),
  ('Anfibol Nebix', 'Nebivolol', '5 mg', 'tableta'::medication_presentation),
  ('Apidra', 'Insulina', '100 U/ml', 'inyectable'::medication_presentation),
  ('Aprovel', 'Irbesartán', '150 mg', 'tableta'::medication_presentation),
  ('Aprovel', 'Irbesartán', '300 mg', 'tableta'::medication_presentation),
  ('Arcalion', 'Sulbutiamina', '200 mg', 'tableta'::medication_presentation),
  ('Aspirina', 'Ácido acetilsalicílico', '100 mg', 'tableta'::medication_presentation),
  ('Aspirina', 'Ácido acetilsalicílico', '300 mg', 'tableta'::medication_presentation),
  ('Aspirina', 'Ácido acetilsalicílico', '325 mg', 'tableta'::medication_presentation),
  ('Aspirina', 'Ácido acetilsalicílico', '50 mg', 'tableta'::medication_presentation),
  ('Aspirina', 'Ácido acetilsalicílico', '80 mg', 'capsula'::medication_presentation),
  ('Aspirina', 'Ácido acetilsalicílico', '81 mg', 'tableta'::medication_presentation),
  ('Atacand', 'Candesartán', '16 mg', 'tableta'::medication_presentation),
  ('Atacand', 'Candesartán', '32 mg', 'tableta'::medication_presentation),
  ('Atacand', 'Candesartán', '8 mg', 'tableta'::medication_presentation),
  ('Atacand Plus', 'Candesartán + Hidroclorotiazida', '16 mg + 12.5 mg', 'tableta'::medication_presentation),
  ('Atacand Plus', 'Candesartán + Hidroclorotiazida', '32 mg + 25 mg', 'tableta'::medication_presentation),
  ('Atenolol', 'Atenolol', '100 mg', 'tableta'::medication_presentation),
  ('Atenolol', 'Atenolol', '25 mg', 'tableta'::medication_presentation),
  ('Atenolol', 'Atenolol', '50 mg', 'tableta'::medication_presentation),
  ('Atorsyn', 'Atorvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Atorvastateg Toma', 'Atorvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Atorvastateg Toma', 'Atorvastatina', '40 mg', 'tableta'::medication_presentation),
  ('Atorvastatina', 'Atorvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Atorvastatina', 'Atorvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Atorvastatina', 'Atorvastatina', '40 mg', 'tableta'::medication_presentation),
  ('Atorvastatina', 'Atorvastatina', '80 mg', 'tableta'::medication_presentation),
  ('Atovastatina', 'Atovastatina', '20 mg', 'tableta'::medication_presentation),
  ('Atrolip', 'Atorvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Atrolip', 'Atorvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Atrolip', 'Atorvastatina', '40 mg', 'tableta'::medication_presentation),
  ('Atrolip', 'Atorvastatina', '80 mg', 'tableta'::medication_presentation),
  ('Augmentin Bid', 'Amoxicilina + Ácido Clavulanico', '1 g', 'tableta'::medication_presentation),
  ('Augmentin Bid', 'Amoxicilina + Ácido Clavulanico', '1000 mg', 'tableta'::medication_presentation),
  ('Augmentin Bid', 'Amoxilina Ácido Nalidixico', '875 mg', 'tableta'::medication_presentation),
  ('Avamys', 'Fluticasona Furoato', '27.5 mcg', 'inhalador'::medication_presentation),
  ('Basaglar', 'Insulina', '100 U/ml', 'inyectable'::medication_presentation),
  ('Benazepril', 'Benazepril', '40 mg', 'tableta'::medication_presentation),
  ('Benicar', 'Olmesartán', '20 mg', 'tableta'::medication_presentation),
  ('Benicar', 'Olmesartán', '40 mg', 'tableta'::medication_presentation),
  ('Benicar', 'Olmesartán', '80 mg', 'tableta'::medication_presentation),
  ('Benicar', 'Olmesartán + Amlodipina', '40 mg + 5 mg', 'tableta'::medication_presentation),
  ('Benicar Amlo', 'Olmesartán + Amlodipina', '20 mg + 5 mg', 'tableta'::medication_presentation),
  ('Benicar Amlo', 'Olmesartán + Amlodipina', '40 mg + 10 mg', 'tableta'::medication_presentation),
  ('Benicar Amlo', 'Olmesartán + Amlodipina', '40 mg + 5 mg', 'tableta'::medication_presentation),
  ('Benicar Iltux', 'Olmesartán', '40 mg', 'tableta'::medication_presentation),
  ('Betaloc ZOK', 'Metoprolol', '100 mg', 'tableta'::medication_presentation),
  ('Betaloc ZOK', 'Metoprolol', '50 mg', 'tableta'::medication_presentation),
  ('Betalock ZOK', 'Metoprolol', '100 mg', 'tableta'::medication_presentation),
  ('Betalock ZOK', 'Metoprolol', '50 mg', 'tableta'::medication_presentation),
  ('Betalock ZOK Otmar', 'Metoprolol', '100 mg', 'tableta'::medication_presentation),
  ('Betalock ZOK Otmar', 'Metoprolol', '50 mg', 'tableta'::medication_presentation),
  ('Betalock Zoc', 'Metoprolol', '100 mg', 'tableta'::medication_presentation),
  ('Betalock Zoc', 'Metoprolol', '25 mg', 'tableta'::medication_presentation),
  ('Betalock Zoc', 'Metoprolol', '50 mg', 'tableta'::medication_presentation),
  ('Betalok ZOK', 'Metoprolol', '100 mg', 'tableta'::medication_presentation),
  ('Betaserc', 'Betahistina', '16 mg', 'tableta'::medication_presentation),
  ('Betistin', 'Betahistina', '16 mg', 'tableta'::medication_presentation),
  ('Betistin', 'Betahistina', '24 mcg', 'tableta'::medication_presentation),
  ('Betistin', 'Betahistina', '24 mg', 'tableta'::medication_presentation),
  ('Binoclar', 'Claritromicina MK', '500 mg', 'tableta'::medication_presentation),
  ('Bisobloc', 'Bisoprolol', '2.5 mg', 'tableta'::medication_presentation),
  ('Bisobloc', 'Bisoprolol', '5 mg', 'tableta'::medication_presentation),
  ('Bisoprolol', 'Bisoprolol', '100 mg', 'tableta'::medication_presentation),
  ('Bisoprolol', 'Bisoprolol', '2.5 mg', 'tableta'::medication_presentation),
  ('Bisoprolol', 'Bisoprolol', '5 mg', 'tableta'::medication_presentation),
  ('Blopress', 'Candesartán', '16 mg', 'tableta'::medication_presentation),
  ('Blopress', 'Candesartán', '32 mg', 'tableta'::medication_presentation),
  ('Blopress', 'Candesartán', '8 mg', 'tableta'::medication_presentation),
  ('Britomar', 'Torasemida', '10 mg', 'tableta'::medication_presentation),
  ('Britomar', 'Torasemida', '5 mg', 'tableta'::medication_presentation),
  ('Broxotan', 'Melatonina + Lúpulo + Valeriana + Pasiflora', '3 mg', 'capsula'::medication_presentation),
  ('Broxotan Plus', 'Melatonina + Lúpulo + Valeriana + Pasiflora', '3 mg', 'capsula'::medication_presentation),
  ('Broxotan Plus', 'Melatonina + Lúpulo + Valeriana + Pasiflora', '5 mg', 'tableta'::medication_presentation),
  ('Budek Plus:', 'Budesonida + Formoterol', '200 mcg', 'tableta'::medication_presentation),
  ('Calox', 'Amlodipina', '5 mg', 'tableta'::medication_presentation),
  ('Calox', 'Irbesartán', '300 mg', 'tableta'::medication_presentation),
  ('Candesartán', 'Candesartán', '16 mg', 'tableta'::medication_presentation),
  ('Candesartán', 'Candesartán', '32 mg', 'tableta'::medication_presentation),
  ('Canfir XR', 'Metformina', '1000 mg', 'tableta'::medication_presentation),
  ('Canfir XR', 'Metformina', '500 mg', 'tableta'::medication_presentation),
  ('Canfix XR', 'Metformina', '1000 mg', 'tableta'::medication_presentation),
  ('Captopril', 'Captopril', '25 mg', 'tableta'::medication_presentation),
  ('Carbimen', 'Lercanidipino', '10 mg', 'tableta'::medication_presentation),
  ('Carbimen', 'Lercanidipino', '20 mg', 'tableta'::medication_presentation),
  ('Carbimen', 'Lercanidipino', '5 mg', 'tableta'::medication_presentation),
  ('Carbimen Dihidrolip', 'Lercanidipino', '10 mg', 'tableta'::medication_presentation),
  ('Carbimen Dihidrolip', 'Lercanidipino', '20 mg', 'tableta'::medication_presentation),
  ('Cardioaspirina', 'Ácido acetilsalicílico', '100 mg', 'tableta'::medication_presentation),
  ('Cardioaspirina', 'Ácido acetilsalicílico', '81 mg', 'tableta'::medication_presentation),
  ('Cardiobloc', 'Amlodipina', '10 mg', 'tableta'::medication_presentation),
  ('Cardiobloc', 'Amlodipina', '5 mg', 'tableta'::medication_presentation),
  ('Cardioblock', 'Amlodipina', '5 mg', 'tableta'::medication_presentation),
  ('Cardiozar', 'Losartán', '100 mg', 'tableta'::medication_presentation),
  ('Cardiozar', 'Losartán', '50 mg', 'tableta'::medication_presentation),
  ('Cardiozar Forte', 'Losartán', '100 mg', 'tableta'::medication_presentation),
  ('Carvedidenk', 'Carvedilol', '25 mg', 'tableta'::medication_presentation),
  ('Carvedidenk', 'Carvedilol', '6.25 mg', 'tableta'::medication_presentation),
  ('Carvedilol', 'Carvedilol', '12.5 mg', 'tableta'::medication_presentation),
  ('Carvedilol', 'Carvedilol', '25 mg', 'tableta'::medication_presentation),
  ('Carvedilol', 'Carvedilol', '6.25 mg', 'tableta'::medication_presentation),
  ('Carvedilol Ccarvediteg', 'Carvedilol Ccarvediteg', '6.25 mg', 'tableta'::medication_presentation),
  ('Caste', 'Tadalafilo', '20 mg', 'tableta'::medication_presentation),
  ('Caste', 'Tadalafilo', '5 mg', 'tableta'::medication_presentation),
  ('Choice', 'Warfarina', '5 mg', 'tableta'::medication_presentation),
  ('Choice Dar', 'Warfarina', '5 mg', 'tableta'::medication_presentation),
  ('Ciclobenzaprina', 'Ciclobenzaprina', '5 mg', 'tableta'::medication_presentation),
  ('Cilostazol', 'Cilostazol', '50 mg', 'tableta'::medication_presentation),
  ('Cipril', 'Cipril', '10 mg', 'tableta'::medication_presentation),
  ('Cipril', 'Cipril', '20 mg', 'tableta'::medication_presentation),
  ('Ciprofibrato', 'Ciprofibrato', '100 mg', 'tableta'::medication_presentation),
  ('Cirpril', 'Cirpril', '10 mg', 'tableta'::medication_presentation),
  ('Cirpril', 'Cirpril', '20 mg', 'tableta'::medication_presentation),
  ('Claritromicina', 'Claritromicina', '500 mg', 'tableta'::medication_presentation),
  ('Clindamicina', 'Clindamicina', '300 mg', 'capsula'::medication_presentation),
  ('Clonazepam', 'Clonazepam', '2 mg', 'tableta'::medication_presentation),
  ('Clopidogrel', 'Clopidogrel', '75 mg', 'tableta'::medication_presentation),
  ('Colber', 'Bisoprolol', '10 mg', 'tableta'::medication_presentation),
  ('Colber', 'Bisoprolol', '2.5 mg', 'tableta'::medication_presentation),
  ('Colber', 'Bisoprolol', '5 mg', 'tableta'::medication_presentation),
  ('Concor', 'Bisoprolol', '10 mg', 'tableta'::medication_presentation),
  ('Concor', 'Bisoprolol', '2.5 mg', 'tableta'::medication_presentation),
  ('Concor', 'Bisoprolol', '5 mg', 'tableta'::medication_presentation),
  ('Controlip', 'Fenofibrato', '160 mg', 'capsula'::medication_presentation),
  ('Cordarone', 'Amiodarona', '200 mg', 'tableta'::medication_presentation),
  ('Coreg', 'Carvedilol', '12.5 mg', 'tableta'::medication_presentation),
  ('Coreg', 'Carvedilol', '25 mg', 'tableta'::medication_presentation),
  ('Coreg', 'Carvedilol', '6.25 mg', 'tableta'::medication_presentation),
  ('Coreg Carvedidenk', 'Carvedilol', '6.25 mg', 'tableta'::medication_presentation),
  ('Corentel', 'Bisoprolol', '10 mg', 'tableta'::medication_presentation),
  ('Corentel', 'Bisoprolol', '5 mg', 'tableta'::medication_presentation),
  ('Cosyrel', 'Bisoprolol + Perindopril', '10 mg + 10 mg', 'tableta'::medication_presentation),
  ('Cosyrel', 'Bisoprolol + Perindopril', '10 mg + 5 mg', 'tableta'::medication_presentation),
  ('Cosyrel', 'Bisoprolol + Perindopril', '5 mg + 10 mg', 'tableta'::medication_presentation),
  ('Cosyrel', 'Bisoprolol + Perindopril', '5 mg + 5 mg', 'tableta'::medication_presentation),
  ('Coveran', 'Perindopril + Amlodipina', '10 mg + 10 mg', 'tableta'::medication_presentation),
  ('Coveran', 'Perindopril + Amlodipina', '3.5 mg + 2.5 mg', 'tableta'::medication_presentation),
  ('Coveran', 'Perindopril + Amlodipina', '5 mg + 10 mg', 'tableta'::medication_presentation),
  ('Coveran', 'Perindopril + Amlodipina', '5 mg + 5 mg', 'tableta'::medication_presentation),
  ('Coversyl', 'Perindopril', '10 mg', 'tableta'::medication_presentation),
  ('Coversyl', 'Perindopril', '5 mg', 'tableta'::medication_presentation),
  ('Cravid', 'Rosuvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Cravid', 'Rosuvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Creom', 'Pancrelipasa', '1000 mg', 'tableta'::medication_presentation),
  ('Cresadex', 'Rosuvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Cresadex', 'Rosuvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Cresadex Plus', 'Ácido fenofíbrico + Rosuvastatina', '10 mg + 10 mg', 'tableta'::medication_presentation),
  ('Cresadex Plus', 'Ácido fenofíbrico + Rosuvastatina', '115 mg + 10 mg', 'tableta'::medication_presentation),
  ('Cresadex Plus', 'Ácido fenofíbrico + Rosuvastatina', '125 mg + 20 mg', 'tableta'::medication_presentation),
  ('Cresadex Plus', 'Ácido fenofíbrico + Rosuvastatina', '135 mcg + 10 mcg', 'tableta'::medication_presentation),
  ('Cresadex Plus', 'Ácido fenofíbrico + Rosuvastatina', '135 mg + 10 mg', 'capsula'::medication_presentation),
  ('Cresadex Plus', 'Ácido fenofíbrico + Rosuvastatina', '135 mg + 20 mg', 'capsula'::medication_presentation),
  ('Cresadex Plus', 'Ácido fenofíbrico + Rosuvastatina', '35 mg + 10 mg', 'tableta'::medication_presentation),
  ('Cresadex Plus Fenovas', 'Ácido fenofíbrico + Rosuvastatina', '135 mg + 10 mg', 'tableta'::medication_presentation),
  ('Cresadex Plus Fenovas', 'Ácido fenofíbrico + Rosuvastatina', '135 mg + 20 mg', 'tableta'::medication_presentation),
  ('Cresadex Plus Tablerta', 'Ácido fenofíbrico + Rosuvastatina', '135 mg + 10 mg', 'tableta'::medication_presentation),
  ('Crestor', 'Rosuvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Crestor', 'Rosuvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Crestor', 'Rosuvastatina', '40 mg', 'tableta'::medication_presentation),
  ('Crestor Cresadex', 'Rosuvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Crestor Cresadex', 'Rosuvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Crestor Tmar', 'Rosuvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Cymbalta', 'Duloxetina', '30 mg', 'capsula'::medication_presentation),
  ('Cymbalta', 'Duloxetina', '60 mg', 'capsula'::medication_presentation),
  ('Daflon', 'Diosmina + Hesperidina', '1 g', 'sobre'::medication_presentation),
  ('Daflon', 'Diosmina + Hesperidina', '1 mg', 'tableta'::medication_presentation),
  ('Daflon', 'Diosmina + Hesperidina', '1000 mg', 'sobre'::medication_presentation),
  ('Daflon', 'Diosmina + Hesperidina', '500 g', 'tableta'::medication_presentation),
  ('Daflon', 'Diosmina + Hesperidina', '500 mg', 'tableta'::medication_presentation),
  ('Daflon Vedipal', 'Diosmina + Hesperidina', '1000 mg', 'tableta'::medication_presentation),
  ('Denk', 'Amlodipina', '10 mg', 'tableta'::medication_presentation),
  ('Denk', 'Carvedilol', '25 mg', 'tableta'::medication_presentation),
  ('Denk', 'Carvedilol', '6.25 mg', 'tableta'::medication_presentation),
  ('Denk', 'Glimepirida', '2 mg', 'tableta'::medication_presentation),
  ('Denk', 'Glimepirida', '3 mg', 'tableta'::medication_presentation),
  ('Denk', 'Losartán', '100 mg', 'tableta'::medication_presentation),
  ('Denk', 'Losartán', '50 mg', 'tableta'::medication_presentation),
  ('Denk', 'Metformina', '1000 mg', 'tableta'::medication_presentation),
  ('Denk', 'Metformina', '500 mg', 'tableta'::medication_presentation),
  ('Denk', 'Metformina', '850 mg', 'tableta'::medication_presentation),
  ('Denk', 'Nifedipina', '20 mg', 'tableta'::medication_presentation),
  ('Denk', 'Pantoprazol', '40 mg', 'tableta'::medication_presentation),
  ('Denk', 'Torasemida', '5 mg', 'tableta'::medication_presentation),
  ('Desarius', 'Desloratadina', '5 mg', 'tableta'::medication_presentation),
  ('Dexlanzopral', 'Dexlansoprazol', '20 mg', 'capsula'::medication_presentation),
  ('Dexlanzopral', 'Dexlansoprazol', '30 mg', 'capsula'::medication_presentation),
  ('Dexlanzopral', 'Dexlansoprazol', '60 mcg', 'tableta'::medication_presentation),
  ('Dexlanzopral', 'Dexlansoprazol', '60 mg', 'capsula'::medication_presentation),
  ('Dextos', 'Dextrometorfano', '27 mg / 15 ml', 'jarabe'::medication_presentation),
  ('Dineurin', 'Gabapentina', '300 mg', 'capsula'::medication_presentation),
  ('Diosmina', 'Diosmina', '500 mg', 'tableta'::medication_presentation),
  ('Diovan', 'Valsartán', '160 mg', 'tableta'::medication_presentation),
  ('Diovan', 'Valsartán', '320 mg', 'tableta'::medication_presentation),
  ('Diovan', 'Valsartán', '80 mg', 'tableta'::medication_presentation),
  ('Dislep', 'Levosulpirida', '25 mg', 'tableta'::medication_presentation),
  ('Dislep', 'Levosulpirida', '25 mg / 1 ml', 'gotas'::medication_presentation),
  ('Dium', 'Pregabalina', '150 mg', 'capsula'::medication_presentation),
  ('Dorixina Relax', 'Clonixinato De Lisina Ciclobenzaprina', '125 mg', 'tableta'::medication_presentation),
  ('Doxiciclina', 'Doxiciclina', '100 mg', 'tableta'::medication_presentation),
  ('Duloxeteg', 'Duloxetina', '30 mg', 'tableta'::medication_presentation),
  ('Duloxetina', 'Duloxetina', '30 mg', 'capsula'::medication_presentation),
  ('Duxetina', 'Duxetina', '60 mg', 'capsula'::medication_presentation),
  ('Efinex', 'Glimepirida', '2 mg', 'tableta'::medication_presentation),
  ('Efinex', 'Glimepirida', '4 mg', 'tableta'::medication_presentation),
  ('Efinex Met', 'Glimepirida + Metformina', '2 mg + 1000 mg', 'tableta'::medication_presentation),
  ('Efinex Met', 'Glimepirida + Metformina', '4 mg + 100 mg', 'tableta'::medication_presentation),
  ('Efinex Met', 'Glimepirida + Metformina', '4 mg + 1000 mg', 'tableta'::medication_presentation),
  ('Empazin', 'Empagliflozina', '10 mg', 'tableta'::medication_presentation),
  ('Empazin', 'Empagliflozina', '25 mg', 'tableta'::medication_presentation),
  ('Empazin Izaban Empiria', 'Empagliflozina', '25 mg', 'tableta'::medication_presentation),
  ('Empiria Duo', 'Empagliflozina + Metformina', '12.5 mg + 1000 mg', 'tableta'::medication_presentation),
  ('Empiria Duo', 'Empagliflozina + Metformina', '12.5 mg + 850 mg', 'tableta'::medication_presentation),
  ('Enalapril', 'Enalapril', '20 mg', 'tableta'::medication_presentation),
  ('Esbelcaps', 'Fenproporex + Diazepam', '20 mg', 'capsula'::medication_presentation),
  ('Esbelcaps', 'Fenproporex + Diazepam', '20 mg + 6 mg', 'capsula'::medication_presentation),
  ('Escitalopram', 'Escitalopram', '5 mg', 'tableta'::medication_presentation),
  ('Esomeprazol', 'Esomeprazol', '20 mg', 'tableta'::medication_presentation),
  ('Espironolactona', 'Espironolactona', '100 mg', 'tableta'::medication_presentation),
  ('Espironolactona', 'Espironolactona', '25 mg', 'tableta'::medication_presentation),
  ('Eukene H', 'Olmesartán + Hidroclorotiazida', '40 mg + 25 mg', 'tableta'::medication_presentation),
  ('Eutirox', 'Levotiroxina', '100 mcg', 'tableta'::medication_presentation),
  ('Eutirox', 'Levotiroxina', '1000 mcg', 'tableta'::medication_presentation),
  ('Eutirox', 'Levotiroxina', '112 mcg', 'tableta'::medication_presentation),
  ('Eutirox', 'Levotiroxina', '125 mcg', 'tableta'::medication_presentation),
  ('Eutirox', 'Levotiroxina', '125 mg', 'tableta'::medication_presentation),
  ('Eutirox', 'Levotiroxina', '150 mcg', 'tableta'::medication_presentation),
  ('Eutirox', 'Levotiroxina', '150 mg', 'tableta'::medication_presentation),
  ('Eutirox', 'Levotiroxina', '175 mcg', 'tableta'::medication_presentation),
  ('Eutirox', 'Levotiroxina', '200 mcg', 'tableta'::medication_presentation),
  ('Eutirox', 'Levotiroxina', '25 mcg', 'tableta'::medication_presentation),
  ('Eutirox', 'Levotiroxina', '25 mg', 'tableta'::medication_presentation),
  ('Eutirox', 'Levotiroxina', '50 mcg', 'tableta'::medication_presentation),
  ('Eutirox', 'Levotiroxina', '50 mg', 'tableta'::medication_presentation),
  ('Eutirox', 'Levotiroxina', '75 mcg', 'tableta'::medication_presentation),
  ('Eutirox', 'Levotiroxina', '75 mg', 'tableta'::medication_presentation),
  ('Eutirox', 'Levotiroxina', '88 mcg', 'tableta'::medication_presentation),
  ('Eutirox Synthroid', 'Levotiroxina', '25 mcg', 'tableta'::medication_presentation),
  ('Eutirox Synthroid', 'Levotiroxina', '50 mcg', 'tableta'::medication_presentation),
  ('Eutirox Syntroid', 'Levotiroxina', '75 mcg', 'tableta'::medication_presentation),
  ('Exforge', 'Valsartán + Amlodipina', '10 mg + 160 mg', 'tableta'::medication_presentation),
  ('Exforge', 'Valsartán + Amlodipina', '10 mg + 320 mg', 'tableta'::medication_presentation),
  ('Exforge', 'Valsartán + Amlodipina', '10 mg + 320 mg + 25 mg', 'tableta'::medication_presentation),
  ('Exforge', 'Valsartán + Amlodipina', '160 mg', 'tableta'::medication_presentation),
  ('Exforge', 'Valsartán + Amlodipina', '160 mg + 10 mg', 'tableta'::medication_presentation),
  ('Exforge', 'Valsartán + Amlodipina', '160 mg + 5 mg', 'tableta'::medication_presentation),
  ('Exforge', 'Valsartán + Amlodipina', '160 mg + 5 mg + 12.5 mg', 'tableta'::medication_presentation),
  ('Exforge', 'Valsartán + Amlodipina', '300 mg + 5 mg', 'tableta'::medication_presentation),
  ('Exforge', 'Valsartán + Amlodipina', '320 mg + 10 mg', 'tableta'::medication_presentation),
  ('Exforge', 'Valsartán + Amlodipina', '320 mg + 5 mg', 'tableta'::medication_presentation),
  ('Exforge', 'Valsartán + Amlodipina', '5 mg + 160 mg', 'tableta'::medication_presentation),
  ('Exforge', 'Valsartán + Amlodipina', '5 mg + 320 mg', 'tableta'::medication_presentation),
  ('Exforge HCT', 'Valsartán + Amlodipina', '10 mg + 160 mg + 12.5 mg', 'tableta'::medication_presentation),
  ('Exforge HCT', 'Valsartán + Amlodipina', '10 mg + 320 mg + 25 mg', 'tableta'::medication_presentation),
  ('Exforge HCT', 'Valsartán + Amlodipina', '160 mg + 5 mg + 12.5 mg', 'tableta'::medication_presentation),
  ('Exforge HCT', 'Valsartán + Amlodipina', '320 mg + 10 mg + 25 mg', 'tableta'::medication_presentation),
  ('Exforge HCT', 'Valsartán + Amlodipina', '5 mg + 160 mg + 12.5 mg', 'tableta'::medication_presentation),
  ('Exforge HCT 7Tableta', 'Valsartán + Amlodipina', '5 mg + 160 mg + 12.5 mg', 'tableta'::medication_presentation),
  ('Exforge HCT Tablet', 'Valsartán + Amlodipina', '10 mg + 320 mg + 25 mg', 'tableta'::medication_presentation),
  ('Exforge Hcr', 'Valsartán + Amlodipina', '10 mg + 320 mg + 25 mg', 'tableta'::medication_presentation),
  ('Ezolium', 'Esomeprazol', '20 mg', 'capsula'::medication_presentation),
  ('Ezolium', 'Esomeprazol', '40 mg', 'capsula'::medication_presentation),
  ('Farmicina', 'Farmicina', '500 mg', 'tableta'::medication_presentation),
  ('Fenofibrato', 'Fenofibrato', '160 mg', 'capsula'::medication_presentation),
  ('Fenofibrato', 'Fenofibrato', '200 mg', 'tableta'::medication_presentation),
  ('Fenovas', 'Fenofibrato + Rosuvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Fenovas', 'Fenofibrato + Rosuvastatina', '135 mg + 10 mg', 'tableta'::medication_presentation),
  ('Fenovas', 'Fenofibrato + Rosuvastatina', '135 mg + 20 mg', 'tableta'::medication_presentation),
  ('Fenovas', 'Fenofibrato + Rosuvastatina', '20 mg', 'capsula'::medication_presentation),
  ('Fenovas Cresadex Plus', 'Fenofibrato + Rosuvastatina', '135 mg + 20 mg', 'tableta'::medication_presentation),
  ('Fenovas Cresadez Plus', 'Fenofibrato + Rosuvastatina', '135 mg + 10 mg', 'tableta'::medication_presentation),
  ('Feximet XR', 'Metformina', '1000 mg', 'tableta'::medication_presentation),
  ('Feximet XR', 'Metformina', '500 mg', 'tableta'::medication_presentation),
  ('Feximet XR', 'Metformina', '750 mg', 'tableta'::medication_presentation),
  ('Fixim', 'Cefixima', '400 mg', 'tableta'::medication_presentation),
  ('Flexure Msm', 'Glucosamina + Condroitina + Msm', '120 mg + 1500 mg + 2400 mg', 'sobre'::medication_presentation),
  ('Flexure Msm', 'Glucosamina + Condroitina + Msm', '1200 mg + 1500 mg + 2400 mg', 'sobre'::medication_presentation),
  ('Flexure Msm', 'Glucosamina + Condroitina + Msm', '1500 mg + 1200 mg + 2400 mg', 'sobre'::medication_presentation),
  ('Flexure Msm', 'Glucosamina + Condroitina + Msm', '2400 mg', 'tableta'::medication_presentation),
  ('Flexure Msm', 'Glucosamina + Condroitina + Msm', '2400 mg + 1200 mg + 1500 mg', 'sobre'::medication_presentation),
  ('Flexure Msm', 'Glucosamina + Condroitina + Msm', '2400 mg + 1500 mg + 1200 mg', 'sobre'::medication_presentation),
  ('Flexure Msm', 'Glucosamina + Condroitina + Msm', '250 mg + 1500 mg + 1200 mg', 'sobre'::medication_presentation),
  ('Flexure Msm', 'Glucosamina + Condroitina + Msm', '2500 mg + 1200 mg + 1500 mg', 'sobre'::medication_presentation),
  ('Flexure Msm', 'Glucosamina + Condroitina + Msm', '2500 mg + 1500 mg + 1200 mg', 'sobre'::medication_presentation),
  ('Flexure Msm', 'Glucosamina + Condroitina + Msm', '2500 mg + 2400 mg + 1200 mg', 'sobre'::medication_presentation),
  ('Fluconazol', 'Fluconazol', '150 mg', 'tableta'::medication_presentation),
  ('Fluoxetina', 'Fluoxetina', '20 mg', 'tableta'::medication_presentation),
  ('Fluzina', 'Flunarizina', '10 mg', 'tableta'::medication_presentation),
  ('Forxiga', 'Dapagliflozina', '10 mg', 'tableta'::medication_presentation),
  ('Forxiga', 'Dapagliflozina', '5 mg', 'tableta'::medication_presentation),
  ('Forxiga Adiplex', 'Dapagliflozina', '10 mg', 'tableta'::medication_presentation),
  ('Forxiga Fanter', 'Dapagliflozina', '10 mg', 'tableta'::medication_presentation),
  ('Furosemida', 'Furosemida', '20 mg', 'inyectable'::medication_presentation),
  ('Furosemida', 'Furosemida', '4 mg', 'tableta'::medication_presentation),
  ('Furosemida', 'Furosemida', '40 mg', 'tableta'::medication_presentation),
  ('Gabapentina', 'Gabapentina', '300 mg', 'capsula'::medication_presentation),
  ('Gabapentina', 'Gabapentina', '400 mg', 'tableta'::medication_presentation),
  ('Gabapentina', 'Gabapentina', '600 mg', 'tableta'::medication_presentation),
  ('Gabictal', 'Gabapentina', '300 mg', 'tableta'::medication_presentation),
  ('Gal', 'Amitriptilina', '25 mg', 'tableta'::medication_presentation),
  ('Galvus', 'Vildagliptina', '50 mg', 'tableta'::medication_presentation),
  ('Galvus Met', 'Vildagliptina + Metformina', '50 mg + 100 mg', 'tableta'::medication_presentation),
  ('Galvus Met', 'Vildagliptina + Metformina', '50 mg + 1000 mg', 'tableta'::medication_presentation),
  ('Galvus Met', 'Vildagliptina + Metformina', '50 mg + 500 mg', 'tableta'::medication_presentation),
  ('Galvus Met', 'Vildagliptina + Metformina', '50 mg + 850 mg', 'tableta'::medication_presentation),
  ('Gastroflux', 'Domperidona', '10 mg', 'tableta'::medication_presentation),
  ('Gastroflux', 'Domperidona', '5 mg / 1 ml', 'tableta'::medication_presentation),
  ('Genfar', 'Losartán', '50 mg', 'tableta'::medication_presentation),
  ('Glargina', 'Insulina', '100 U/ml', 'inyectable'::medication_presentation),
  ('Glaritus', 'Insulina', '100 U/ml', 'inyectable'::medication_presentation),
  ('Glibenclamida', 'Glibenclamida', '5 mg', 'tableta'::medication_presentation),
  ('Gliclazida', 'Gliclazida', '60 mg', 'tableta'::medication_presentation),
  ('Glimepirida', 'Glimepirida', '2 mg', 'tableta'::medication_presentation),
  ('Glimepirida', 'Glimepirida', '4 mg', 'tableta'::medication_presentation),
  ('Glisulin', 'Metformina', '1000 mg', 'tableta'::medication_presentation),
  ('Glisulin', 'Metformina', '500 mg', 'tableta'::medication_presentation),
  ('Glisulin', 'Metformina', '750 mg', 'tableta'::medication_presentation),
  ('Glisulin', 'Metformina', '850 mg', 'tableta'::medication_presentation),
  ('Glisulin XR', 'Metformina', '1 g', 'tableta'::medication_presentation),
  ('Glisulin XR', 'Metformina', '100 mg', 'tableta'::medication_presentation),
  ('Glisulin XR', 'Metformina', '1000 mg', 'tableta'::medication_presentation),
  ('Glisulin XR', 'Metformina', '500 mg', 'tableta'::medication_presentation),
  ('Glisulin XR', 'Metformina', '750 mg', 'tableta'::medication_presentation),
  ('Glisulin XR', 'Metformina', '850 mg', 'tableta'::medication_presentation),
  ('Glisulin XR Tablet', 'Metformina', '750 mg', 'tableta'::medication_presentation),
  ('H', 'Irbesartán + HCT MK Bart', '300 mg + 12.5 mg', 'tableta'::medication_presentation),
  ('Hamolog', 'Insulina', '100 U/ml', 'inyectable'::medication_presentation),
  ('Hidroclorotiazida', 'Hidroclorotiazida', '25 mg', 'tableta'::medication_presentation),
  ('Hiperlipen', 'Ciprofibrato', '10 mg', 'tableta'::medication_presentation),
  ('Hiperlipen', 'Ciprofibrato', '100 mg', 'tableta'::medication_presentation),
  ('Hiperlipen Lipodex', 'Ciprofibrato', '100 mg', 'tableta'::medication_presentation),
  ('Hiperlipen Tsbleta', 'Ciprofibrato', '100 mg', 'tableta'::medication_presentation),
  ('Humalog', 'Insulina', '100 U/ml', 'inyectable'::medication_presentation),
  ('Humulin', 'Insulina', '100 U/ml', 'inyectable'::medication_presentation),
  ('Humulog', 'Insulina', '100 U/ml', 'inyectable'::medication_presentation),
  ('Hytrin', 'Terazosina', '2 mg', 'tableta'::medication_presentation),
  ('Hytrin', 'Terazosina', '5 mg', 'tableta'::medication_presentation),
  ('Iltux', 'Olmesartán', '20 mg', 'tableta'::medication_presentation),
  ('Iltux', 'Olmesartán', '40 mg', 'tableta'::medication_presentation),
  ('Iltux HCT', 'Olmesartán + Hidroclorotiazida', '40 mg + 25 mg', 'tableta'::medication_presentation),
  ('Iltux HCT Benicar HCT', 'Olmesartán + Hidroclorotiazida', '40 mg + 12.5 mg', 'tableta'::medication_presentation),
  ('Iltuxam', 'Olmesartán + Amlodipina', '20 mg + 5 mg', 'tableta'::medication_presentation),
  ('Iltuxam', 'Olmesartán + Amlodipina', '40 mg + 10 mg', 'tableta'::medication_presentation),
  ('Iltuxam', 'Olmesartán + Amlodipina', '40 mg + 5 mg', 'tableta'::medication_presentation),
  ('Iltuxam HCT', 'Olmesartán + Amlodipina', '40 mg + 10 mg + 25 mg', 'tableta'::medication_presentation),
  ('Iltuxam HCT', 'Olmesartán + Amlodipina', '40 mg + 5 mg + 12.5 mg', 'tableta'::medication_presentation),
  ('Iltuxam HCT', 'Olmesartán + Amlodipina', '40 mg + 5 mg + 25 mg', 'tableta'::medication_presentation),
  ('Imbys', 'Azitromicina', '500 mg', 'tableta'::medication_presentation),
  ('Insulex', 'Insulina', '100 U/ml', 'inyectable'::medication_presentation),
  ('Invokana', 'Canagliflozina', '150 mg', 'tableta'::medication_presentation),
  ('Invokana', 'Canagliflozina', '300 mg', 'tableta'::medication_presentation),
  ('Irbersartan', 'Irbersartan', '150 mg', 'tableta'::medication_presentation),
  ('Irbersartan', 'Irbersartan', '300 mg', 'tableta'::medication_presentation),
  ('Irbesartán', 'Irbesartán', '100 mg', 'tableta'::medication_presentation),
  ('Irbesartán', 'Irbesartán', '150 mg', 'tableta'::medication_presentation),
  ('Irbesartán', 'Irbesartán', '300 mg', 'tableta'::medication_presentation),
  ('Irbesartán', 'Irbesartán', '75 mg', 'tableta'::medication_presentation),
  ('Isoptin SR', 'Verapamilo', '120 mg', 'tableta'::medication_presentation),
  ('Isoptin SR', 'Verapamilo', '240 mg', 'tableta'::medication_presentation),
  ('Iveprax', 'Irbesartán', '150 mg', 'tableta'::medication_presentation),
  ('Iveprax', 'Irbesartán', '300 mg', 'tableta'::medication_presentation),
  ('Jalra', 'Vildagliptina', '50 mg', 'tableta'::medication_presentation),
  ('Januvia', 'Sitagliptina', '100 mg', 'tableta'::medication_presentation),
  ('Kombiglyze XR', 'Saxagliptina + Metformina', '5 mg + 1000 mg', 'tableta'::medication_presentation),
  ('Kombiglyze XR', 'Saxagliptina + Metformina', '50 mg + 1000 mg', 'tableta'::medication_presentation),
  ('Kwikpen', 'Insulina Humalog', '100 U/ml', 'inyectable'::medication_presentation),
  ('Lantus', 'Insulina', '100 U/ml', 'inyectable'::medication_presentation),
  ('Lapicera', 'Insulina Semglee U Ml', '100 U', 'inyectable'::medication_presentation),
  ('Lapicera', 'Insulina Tresiba', '100 U/ml', 'inyectable'::medication_presentation),
  ('Lasix', 'Furosemida', '40 mg', 'tableta'::medication_presentation),
  ('Levotiroxina', 'Levotiroxina', '100 mcg', 'tableta'::medication_presentation),
  ('Levotiroxina', 'Levotiroxina', '125 mcg', 'tableta'::medication_presentation),
  ('Levotiroxina', 'Levotiroxina', '150 mcg', 'tableta'::medication_presentation),
  ('Levotiroxina', 'Levotiroxina', '25 mcg', 'tableta'::medication_presentation),
  ('Levotiroxina', 'Levotiroxina', '50 mcg', 'tableta'::medication_presentation),
  ('Levotiroxina', 'Levotiroxina', '75 mcg', 'tableta'::medication_presentation),
  ('Levoxetina', 'Levoxetina', '750 mg', 'tableta'::medication_presentation),
  ('Lipitor', 'Atorvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Lipitor', 'Atorvastatina', '40 mg', 'tableta'::medication_presentation),
  ('Lipitor', 'Atorvastatina', '80 mg', 'tableta'::medication_presentation),
  ('Lipotic', 'Ácido Tioctico', '600 mg', 'tableta'::medication_presentation),
  ('Lisinopril', 'Lisinopril', '10 mg', 'tableta'::medication_presentation),
  ('Lisinopril', 'Lisinopril', '2.5 mg', 'tableta'::medication_presentation),
  ('Lisinopril', 'Lisinopril', '20 mg', 'tableta'::medication_presentation),
  ('Lisinopril', 'Lisinopril', '40 mg', 'tableta'::medication_presentation),
  ('Lisinopril', 'Lisinopril', '5 mg', 'tableta'::medication_presentation),
  ('Loratadina', 'Loratadina', '10 mg', 'tableta'::medication_presentation),
  ('Lorazepam', 'Lorazepam', '2 mg', 'tableta'::medication_presentation),
  ('Losartán', 'Losartán', '100 mg', 'tableta'::medication_presentation),
  ('Losartán', 'Losartán', '50 mg', 'tableta'::medication_presentation),
  ('Lovastatina', 'Lovastatina', '20 mg', 'tableta'::medication_presentation),
  ('Lovastatina', 'Lovastatina', '40 mg', 'tableta'::medication_presentation),
  ('Lyrica', 'Pregabalina', '150 mg', 'capsula'::medication_presentation),
  ('Lyrica', 'Pregabalina', '75 mg', 'capsula'::medication_presentation),
  ('MR', 'Trimetazidina', '35 mg', 'tableta'::medication_presentation),
  ('Meditor', 'Atorvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Meformina', 'Meformina', '850 mg', 'tableta'::medication_presentation),
  ('Melex', 'Mexazolam', '1 g', 'tableta'::medication_presentation),
  ('Melex', 'Mexazolam', '1 mg', 'tableta'::medication_presentation),
  ('Metforal', 'Metformina', '1000 mg', 'tableta'::medication_presentation),
  ('Metforal', 'Metformina', '500 mg', 'tableta'::medication_presentation),
  ('Metforal', 'Metformina', '850 mg', 'tableta'::medication_presentation),
  ('Metforal XR', 'Metformina', '1000 mg', 'tableta'::medication_presentation),
  ('Metformina', 'Metformina', '1 g', 'tableta'::medication_presentation),
  ('Metformina', 'Metformina', '1000 mg', 'tableta'::medication_presentation),
  ('Metformina', 'Metformina', '2000 mg', 'tableta'::medication_presentation),
  ('Metformina', 'Metformina', '500 mg', 'tableta'::medication_presentation),
  ('Metformina', 'Metformina', '850 g', 'tableta'::medication_presentation),
  ('Metformina', 'Metformina', '850 mg', 'tableta'::medication_presentation),
  ('Metformina Denk', 'Metformina', '1000 mg', 'tableta'::medication_presentation),
  ('Metformina Denk', 'Metformina', '500 mg', 'tableta'::medication_presentation),
  ('Metformina Denk', 'Metformina', '850 mg', 'tableta'::medication_presentation),
  ('Metforteg', 'Metformina', '850 mg', 'tableta'::medication_presentation),
  ('Metglital', 'Glimepirida + Metformina', '2 mg + 1000 mg', 'tableta'::medication_presentation),
  ('Metglital', 'Glimepirida + Metformina', '2 mg + 850 mg', 'tableta'::medication_presentation),
  ('Metglital', 'Glimepirida + Metformina', '4 mg + 1000 mg', 'tableta'::medication_presentation),
  ('Metglital Lex', 'Glimepirida + Metformina', '2 mg + 850 mg', 'tableta'::medication_presentation),
  ('Metglital Lex', 'Glimepirida + Metformina', '4 mg + 1000 mg', 'tableta'::medication_presentation),
  ('Metglital Lex', 'Glimepirida + Metformina', '4 mg + 850 mg', 'tableta'::medication_presentation),
  ('Metglital Lex', 'Glimepirida + Metformina', '850 mg + 2 mg', 'tableta'::medication_presentation),
  ('Metglital Lex', 'Glimepirida + Metformina', '850 mg + 4 mg', 'tableta'::medication_presentation),
  ('Metglucol', 'Metformina', '1000 mg', 'tableta'::medication_presentation),
  ('Metglucol', 'Metformina', '500 mg', 'tableta'::medication_presentation),
  ('Metglucol', 'Metformina', '850 mg', 'tableta'::medication_presentation),
  ('Metiom', 'Esomeprazol', '20 mg', 'tableta'::medication_presentation),
  ('Metiom', 'Esomeprazol', '40 mg', 'capsula'::medication_presentation),
  ('Metoprolol', 'Metoprolol', '100 mg', 'tableta'::medication_presentation),
  ('Metoprolol', 'Metoprolol', '25 mg', 'tableta'::medication_presentation),
  ('Metoprolol', 'Metoprolol', '50 mg', 'tableta'::medication_presentation),
  ('Metronidazol', 'Metronidazol', '500 mg', 'tableta'::medication_presentation),
  ('Micardis', 'Telmisartán', '40 mg', 'tableta'::medication_presentation),
  ('Micardis', 'Telmisartán', '80 mg', 'tableta'::medication_presentation),
  ('Micardis', 'Telmisartán + Hidroclorotiazida', '80 mg + 12.5 mg', 'tableta'::medication_presentation),
  ('Micardis Duo', 'Telmisartán + Amlodipina', '80 mg + 10 mg', 'tableta'::medication_presentation),
  ('Micardis Duo', 'Telmisartán + Amlodipina', '80 mg + 5 mg', 'tableta'::medication_presentation),
  ('Micardis Plus', 'Telmisartán + Hidroclorotiazida', '80 mg', 'tableta'::medication_presentation),
  ('Micardis Plus', 'Telmisartán + Hidroclorotiazida', '80 mg + 12.5 mg', 'tableta'::medication_presentation),
  ('Micardis Siprotec', 'Telmisartán', '80 mg', 'tableta'::medication_presentation),
  ('Minart', 'Candesartán', '16 mg', 'tableta'::medication_presentation),
  ('Minart', 'Candesartán', '8 mg', 'tableta'::medication_presentation),
  ('Mix', 'Insulina Humalog', '100 U/ml', 'inyectable'::medication_presentation),
  ('Montelukast', 'Montelukast', '10 mg', 'tableta'::medication_presentation),
  ('Musculare', 'Ciclobenzaprina', '10 mg', 'tableta'::medication_presentation),
  ('Musculare', 'Ciclobenzaprina', '5 mg', 'tableta'::medication_presentation),
  ('Mwetformina', 'Mwetformina', '850 mg', 'tableta'::medication_presentation),
  ('Nabrantin', 'Clopidogrel', '75 mg', 'tableta'::medication_presentation),
  ('Nabratin', 'Clopidogrel', '75 mg', 'tableta'::medication_presentation),
  ('Natrilix', 'Indapamida', '1.5 mg', 'tableta'::medication_presentation),
  ('Natrilix SR', 'Indapamida', '1.5 mg', 'tableta'::medication_presentation),
  ('Natrixam', 'Indapamida + Amlodipina', '1.5 mg + 10 mg', 'tableta'::medication_presentation),
  ('Natrixam', 'Indapamida + Amlodipina', '1.5 mg + 5 mg', 'tableta'::medication_presentation),
  ('Natrixan', 'Indapamida + Amlodipina', '1.5 mg + 10 mg', 'tableta'::medication_presentation),
  ('Natrixan', 'Indapamida + Amlodipina', '1.5 mg + 5 mg', 'tableta'::medication_presentation),
  ('Nebilet', 'Nebivolol', '5 mg', 'tableta'::medication_presentation),
  ('Nebilet Anfibol', 'Nebivolol', '5 mg', 'tableta'::medication_presentation),
  ('Nebilet Nebix', 'Nebivolol', '5 mg', 'tableta'::medication_presentation),
  ('Nebilet Plus', 'Nebivolol + Hidroclorotiazida', '5 mg + 12.5 mg', 'tableta'::medication_presentation),
  ('Nebilet Plus', 'Nebivolol + Hidroclorotiazida', '5 mg + 25 mg', 'tableta'::medication_presentation),
  ('Nebivolol', 'Nebivolol', '5 mg', 'tableta'::medication_presentation),
  ('Nebix', 'Nebivolol', '5 mg', 'tableta'::medication_presentation),
  ('Nefedipina', 'Nefedipina', '20 mg', 'tableta'::medication_presentation),
  ('Neupax', 'Fluoxetina', '20 mg', 'tableta'::medication_presentation),
  ('Neuronal', 'Pregabalina', '75 mg', 'capsula'::medication_presentation),
  ('Nevibolol', 'Nebivolol', '5 mg', 'tableta'::medication_presentation),
  ('Nexium', 'Esomeprazol', '10 mg', 'sobre'::medication_presentation),
  ('Nexium', 'Esomeprazol', '20 mg', 'tableta'::medication_presentation),
  ('Nexium', 'Esomeprazol', '40 mcg', 'tableta'::medication_presentation),
  ('Nexium', 'Esomeprazol', '40 mg', 'tableta'::medication_presentation),
  ('Nifedipina', 'Nifedipina', '10 mg', 'tableta'::medication_presentation),
  ('Nifedipina', 'Nifedipina', '20 mg', 'tableta'::medication_presentation),
  ('Nifedipina', 'Nifedipina', '30 mg', 'tableta'::medication_presentation),
  ('Nifedipino', 'Nifedipino', '20 mg', 'tableta'::medication_presentation),
  ('Nizoral', 'Ketoconazol', '40 g', 'crema'::medication_presentation),
  ('Nor Lodipina', 'Nor Lodipina', '5 mg', 'tableta'::medication_presentation),
  ('Nor Sartan', 'Nor Sartan', '50 mg', 'tableta'::medication_presentation),
  ('Normon', 'Lisinopril', '20 mg', 'tableta'::medication_presentation),
  ('Norpurinol', 'Alopurinol', '300 mg', 'tableta'::medication_presentation),
  ('Norsartan', 'Norsartan', '50 mg', 'tableta'::medication_presentation),
  ('Nortiazida', 'Hidroclorotiazida', '25 mg', 'tableta'::medication_presentation),
  ('Nortriptol', 'Amitriptilina', '25 mg', 'tableta'::medication_presentation),
  ('Nortryptol', 'Amitriptilina', '25 mg', 'tableta'::medication_presentation),
  ('Nortryptol Ttableta', 'Amitriptilina', '25 mg', 'tableta'::medication_presentation),
  ('Norvastan', 'Simvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Novolog', 'Insulina', '100 U/ml', 'inyectable'::medication_presentation),
  ('Novorapid', 'Insulina', '100 U/ml', 'inyectable'::medication_presentation),
  ('Nucleo CMP Forte', 'Citidina + Uridina', '3 mg + 6 mg', 'capsula'::medication_presentation),
  ('Nucleo CMP Forte', 'Citidina + Uridina', '5 mg', 'capsula'::medication_presentation),
  ('Nucleo CMP Forte', 'Citidina + Uridina', '5 mg + 3 mg', 'capsula'::medication_presentation),
  ('Oblax', 'Sitagliptina + Metformina', '50 mg + 1000 mg', 'tableta'::medication_presentation),
  ('Oblax', 'Sitagliptina + Metformina', '50 mg + 500 mg', 'tableta'::medication_presentation),
  ('Oblax XR', 'Sitagliptina + Metformina', '100 mg + 1000 mg', 'tableta'::medication_presentation),
  ('Odasen', 'Sitagliptina', '50 mg', 'tableta'::medication_presentation),
  ('Odica', 'Pregabalina', '150 mg', 'capsula'::medication_presentation),
  ('Odica', 'Pregabalina', '300 mg', 'tableta'::medication_presentation),
  ('Odica', 'Pregabalina', '50 mg', 'capsula'::medication_presentation),
  ('Odica', 'Pregabalina', '75 mg', 'capsula'::medication_presentation),
  ('Olmersartan', 'Olmersartan', '20 mg', 'tableta'::medication_presentation),
  ('Olmesartán', 'Olmesartán', '20 mg', 'tableta'::medication_presentation),
  ('Olmesartán', 'Olmesartán', '40 mg', 'tableta'::medication_presentation),
  ('Omeprazol', 'Omeprazol', '20 mg', 'tableta'::medication_presentation),
  ('Ozempic', 'Semaglutida', '0.25 mg', 'inyectable'::medication_presentation),
  ('Ozempic', 'Semaglutida', '2 mg / 1.5 ml', 'inyectable'::medication_presentation),
  ('Ozempic', 'Semaglutida', '4 mg / 3 ml', 'inyectable'::medication_presentation),
  ('Ozempic Dual Dose', 'Semaglutida', '0.25 mg', 'inyectable'::medication_presentation),
  ('Ozempic Dual Dose', 'Semaglutida', '0.5 mg', 'inyectable'::medication_presentation),
  ('Ozempic Dual Dose', 'Semaglutida', '2 mg / 1.5 ml', 'inyectable'::medication_presentation),
  ('Ozempic Dual Dose', 'Semaglutida', '4 mg / 3 ml', 'inyectable'::medication_presentation),
  ('Ozempic Dualdose', 'Semaglutida', '0.5 mg', 'inyectable'::medication_presentation),
  ('Ozempic Dualdose', 'Semaglutida', '2 mg / 1.5 ml', 'inyectable'::medication_presentation),
  ('Ozempic Dualdose', 'Semaglutida', '4 mg / 3 ml', 'inyectable'::medication_presentation),
  ('Ozempic Fix Dose', 'Semaglutida', '4 mg / 3 ml', 'inyectable'::medication_presentation),
  ('Ozempic Fixdose', 'Semaglutida', '1 mg', 'inyectable'::medication_presentation),
  ('Ozempic Fixdose', 'Semaglutida', '4 mg / 3 ml', 'inyectable'::medication_presentation),
  ('Pantoprazol', 'Pantoprazol', '40 mg', 'tableta'::medication_presentation),
  ('Paracetamol', 'Paracetamol', '1 g', 'tableta'::medication_presentation),
  ('Paracetamol', 'Paracetamol', '500 g', 'tableta'::medication_presentation),
  ('Paracetamol', 'Paracetamol', '500 mg', 'tableta'::medication_presentation),
  ('Paxil', 'Paroxetina', '20 mg', 'tableta'::medication_presentation),
  ('Paxil', 'Paroxetina', '25 mg', 'tableta'::medication_presentation),
  ('Phamesenid', 'Furosemida', '40 mg', 'tableta'::medication_presentation),
  ('Pharmesenid', 'Furosemida', '20 mg', 'tableta'::medication_presentation),
  ('Pharmesenid', 'Furosemida', '40 mg', 'tableta'::medication_presentation),
  ('Pharmesenid Pero', 'Furosemida', '40 mg', 'tableta'::medication_presentation),
  ('Pioglitazona', 'Pioglitazona', '15 mg', 'tableta'::medication_presentation),
  ('Pioglitazona', 'Pioglitazona', '30 mg', 'tableta'::medication_presentation),
  ('Pioglitec', 'Pioglitazona', '15 mg', 'tableta'::medication_presentation),
  ('Pioglitec', 'Pioglitazona', '30 mg', 'tableta'::medication_presentation),
  ('Pioglitec Toamr', 'Pioglitazona', '30 mg', 'tableta'::medication_presentation),
  ('Plavix', 'Clopidogrel', '75 mg', 'tableta'::medication_presentation),
  ('Prebictal', 'Pregabalina', '150 mg', 'capsula'::medication_presentation),
  ('Prebictal', 'Pregabalina', '50 mg', 'capsula'::medication_presentation),
  ('Prebictal', 'Pregabalina', '75 mg', 'capsula'::medication_presentation),
  ('Pregabalina', 'Pregabalina', '150 mg', 'capsula'::medication_presentation),
  ('Pregabalina', 'Pregabalina', '300 mg', 'tableta'::medication_presentation),
  ('Pregabalina', 'Pregabalina', '75 mg', 'capsula'::medication_presentation),
  ('Preterax', 'Perindopril + Indapamida', '10 mg + 2.5 mg', 'tableta'::medication_presentation),
  ('Preterax', 'Perindopril + Indapamida', '5 mg', 'tableta'::medication_presentation),
  ('Preterax', 'Perindopril + Indapamida', '5 mg + 1.25 mg', 'tableta'::medication_presentation),
  ('Propal', 'Propranolol', '10 mg', 'tableta'::medication_presentation),
  ('Propal', 'Propranolol', '20 mg', 'tableta'::medication_presentation),
  ('Propal', 'Propranolol', '40 mg', 'tableta'::medication_presentation),
  ('Propanolol', 'Propranolol', '10 mg', 'tableta'::medication_presentation),
  ('Propanolol', 'Propranolol', '40 mg', 'tableta'::medication_presentation),
  ('Provastatina', 'Provastatina', '40 mg', 'tableta'::medication_presentation),
  ('Psicosoma', 'Bromhidrato Del Glutamato De Magnesio', '0.1 mg', 'tableta'::medication_presentation),
  ('Psicosoma', 'Bromhidrato Del Glutamato De Magnesio', '0.15 g', 'tableta'::medication_presentation),
  ('Psicosoma', 'Bromhidrato Del Glutamato De Magnesio', '0.150 g', 'tableta'::medication_presentation),
  ('Psicosoma', 'Bromhidrato Del Glutamato De Magnesio', '0.150 mg', 'tableta'::medication_presentation),
  ('Psicosoma', 'Bromhidrato Del Glutamato De Magnesio', '150 mg', 'tableta'::medication_presentation),
  ('Psicosoma Gragea', 'Bromhidrato Del Glutamato De Magnesio', '0.15 g', 'tableta'::medication_presentation),
  ('Purinox', 'Alopurinol', '300 mg', 'tableta'::medication_presentation),
  ('Quetiapina', 'Quetiapina', '100 mg', 'tableta'::medication_presentation),
  ('Quetiapina', 'Quetiapina', '25 mg', 'tableta'::medication_presentation),
  ('Quetidin', 'Quetiapina', '100 mg', 'tableta'::medication_presentation),
  ('Quetidin', 'Quetiapina', '25 mg', 'tableta'::medication_presentation),
  ('Quetidin Stoxec', 'Quetiapina', '25 mg', 'tableta'::medication_presentation),
  ('Ramipril', 'Ramipril', '2.5 mg', 'tableta'::medication_presentation),
  ('Redotex', 'Triiodotironina + Norpseudoefedrina + Atropina + Aloina + Diazepam', '50 mg', 'capsula'::medication_presentation),
  ('Reglutol', 'Rosuvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Reglutol', 'Rosuvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Regular', 'Insulina Humulin', '100 U/ml', 'inyectable'::medication_presentation),
  ('Regutol', 'Rosuvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Regutol', 'Rosuvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Regutol Cravid', 'Rosuvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Regutol Cresadex', 'Rosuvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Relvar', 'Fluticasona Furoato + Vilanterol', '100 mcg + 25 mcg', 'inhalador'::medication_presentation),
  ('Relvar', 'Fluticasona Furoato + Vilanterol', '100 mg + 25 mg', 'tableta'::medication_presentation),
  ('Reumon', 'Diclofenaco Dietilamina', '40 g', 'gel'::medication_presentation),
  ('Rivotril', 'Clonazepam', '0.5 mg', 'tableta'::medication_presentation),
  ('Rivotril', 'Clonazepam', '2 mg', 'tableta'::medication_presentation),
  ('Rostor', 'Rosuvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Rostor', 'Rosuvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Rostor Cravid Cresadex', 'Rosuvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Rostor Cresadex', 'Rosuvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Rosuvastatina', 'Rosuvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Rosuvastatina', 'Rosuvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Rosuvastatina', 'Rosuvastatina', '40 mg', 'tableta'::medication_presentation),
  ('Rosuvastatina', 'Rosuvastatina', '5 mg', 'tableta'::medication_presentation),
  ('Rosuvasteg', 'Rosuvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Rovaril', 'Rosuvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Rythmonor', 'Propafenona', '150 mg', 'tableta'::medication_presentation),
  ('Rythmonorm', 'Propafenona', '150 mg', 'tableta'::medication_presentation),
  ('Rytmonorm', 'Propafenona', '150 mg', 'tableta'::medication_presentation),
  ('Saimed', 'Metformina', '850 mg', 'tableta'::medication_presentation),
  ('Sanfer', 'Duxetina', '60 mg', 'capsula'::medication_presentation),
  ('Secnidazol', 'Secnidazol', '500 mg', 'tableta'::medication_presentation),
  ('Semglee', 'Insulina', '100 U/ml', 'inyectable'::medication_presentation),
  ('Senokot', 'Senosidos', '8.6 mg', 'tableta'::medication_presentation),
  ('Sertralina', 'Sertralina', '100 mg', 'tableta'::medication_presentation),
  ('Sertralina', 'Sertralina', '50 mg', 'tableta'::medication_presentation),
  ('Sertrateg', 'Sertralina', '50 mg', 'tableta'::medication_presentation),
  ('Sildex', 'Espironolactona', '25 mg', 'tableta'::medication_presentation),
  ('Simvastatina', 'Simvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Simvastatina', 'Simvastatina', '40 mg', 'tableta'::medication_presentation),
  ('Sinvastatina', 'Simvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Sinvastatina', 'Simvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Sinvastatina', 'Simvastatina', '40 mg', 'tableta'::medication_presentation),
  ('Sinvastatina Denk', 'Simvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Siprotec', 'Telmisartán', '80 mg', 'tableta'::medication_presentation),
  ('Siprotec Plus', 'Telmisartán + Hidroclorotiazida', '80 mg + 12.5 mg', 'tableta'::medication_presentation),
  ('Sitadin', 'Sitagliptina', '100 mg', 'tableta'::medication_presentation),
  ('Sitagliptina', 'Sitagliptina', '100 mg', 'tableta'::medication_presentation),
  ('Skar', 'Rosuvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Skar', 'Rosuvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Slidex', 'Espironolactona', '25 mg', 'tableta'::medication_presentation),
  ('Solucaps', 'Mazindol', '2 mg', 'capsula'::medication_presentation),
  ('Star', 'Insulina Lantus Solo', '100 U/ml', 'inyectable'::medication_presentation),
  ('Star', 'Insulina Toujeo Solo', '300 U/ml', 'inyectable'::medication_presentation),
  ('Stimol', 'Citrulina Malato', '1 g', 'sobre'::medication_presentation),
  ('Stimol', 'Citrulina Malato', '5 g', 'sobre'::medication_presentation),
  ('Stimol ._Tomar', 'Citrulina Malato', '1 g', 'sobre'::medication_presentation),
  ('Storvas', 'Atorvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Storvas', 'Atorvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Storvas', 'Atorvastatina', '40 mg', 'tableta'::medication_presentation),
  ('Storvas Toma', 'Atorvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Storvasc', 'Atorvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Storvasc', 'Atorvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Syldex', 'Espironolactona =', '25 mg', 'tableta'::medication_presentation),
  ('Symbicort', 'Budesonida + Formoterol', '160 mcg + 4.5 mcg', 'otro'::medication_presentation),
  ('Symbicort Rapihaler', 'Budesonida + Formoterol', '160 mg + 4.5 mg', 'tableta'::medication_presentation),
  ('Synthroid', 'Levotiroxina', '100 mcg', 'tableta'::medication_presentation),
  ('Synthroid', 'Levotiroxina', '112 mcg', 'tableta'::medication_presentation),
  ('Synthroid', 'Levotiroxina', '125 mcg', 'tableta'::medication_presentation),
  ('Synthroid', 'Levotiroxina', '150 mcg', 'tableta'::medication_presentation),
  ('Synthroid', 'Levotiroxina', '175 mcg', 'tableta'::medication_presentation),
  ('Synthroid', 'Levotiroxina', '188 mcg', 'tableta'::medication_presentation),
  ('Synthroid', 'Levotiroxina', '200 mcg', 'tableta'::medication_presentation),
  ('Synthroid', 'Levotiroxina', '25 mcg', 'tableta'::medication_presentation),
  ('Synthroid', 'Levotiroxina', '25 mg', 'tableta'::medication_presentation),
  ('Synthroid', 'Levotiroxina', '50 mcg', 'tableta'::medication_presentation),
  ('Synthroid', 'Levotiroxina', '75 mcg', 'tableta'::medication_presentation),
  ('Synthroid', 'Levotiroxina', '88 mcg', 'tableta'::medication_presentation),
  ('Synthroid Eutirox', 'Levotiroxina', '100 mcg', 'tableta'::medication_presentation),
  ('Synthroid Eutirox', 'Levotiroxina', '125 mcg', 'tableta'::medication_presentation),
  ('Tablea', 'Nebivolol', '5 mg', 'tableta'::medication_presentation),
  ('Tablet', 'Aspirina', '100 mg', 'tableta'::medication_presentation),
  ('Tapazol', 'Tapazol', '5 mg', 'tableta'::medication_presentation),
  ('Telidalt Plus', 'Telmisartán + Hidroclorotiazida', '80 mg + 12.5 mg', 'tableta'::medication_presentation),
  ('Telmisartán', 'Telmisartán', '40 mg', 'tableta'::medication_presentation),
  ('Telmisartán', 'Telmisartán', '80 mg', 'tableta'::medication_presentation),
  ('Terazocina', 'Terazosina', '5 mg', 'tableta'::medication_presentation),
  ('Terazosina', 'Terazosina', '5 mg', 'tableta'::medication_presentation),
  ('Tinactol', 'Ácido Tioctico', '600 mg', 'tableta'::medication_presentation),
  ('Tioneurol', 'Ácido Tioctico', '600 mg', 'tableta'::medication_presentation),
  ('Torasemida', 'Torasemida', '10 mg', 'tableta'::medication_presentation),
  ('Torasemida', 'Torasemida', '5 mg', 'tableta'::medication_presentation),
  ('Toreza', 'Rosuvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Toreza', 'Rosuvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Toujeo', 'Insulina', '100 U/ml', 'inyectable'::medication_presentation),
  ('Toujeo', 'Insulina', '300 U/ml', 'inyectable'::medication_presentation),
  ('Toujeu', 'Insulina', '100 U/ml', 'inyectable'::medication_presentation),
  ('Toujeu', 'Insulina', '300 U/ml', 'inyectable'::medication_presentation),
  ('Tramadol', 'Paracetamol', '325 mg', 'tableta'::medication_presentation),
  ('Trayenta', 'Linagliptina', '5 mg', 'tableta'::medication_presentation),
  ('Trayenta Duo', 'Linagliptina + Metformina', '12.5 mg + 1000 mg', 'tableta'::medication_presentation),
  ('Trayenta Duo', 'Linagliptina + Metformina', '2.5 mg + 1000 mg', 'tableta'::medication_presentation),
  ('Trayenta Duo', 'Linagliptina + Metformina', '2.5 mg + 500 mg', 'tableta'::medication_presentation),
  ('Trayenta Duo', 'Linagliptina + Metformina', '2.5 mg + 850 mg', 'tableta'::medication_presentation),
  ('Trayenta Duo', 'Linagliptina + Metformina', '50 mg + 1000 mg', 'tableta'::medication_presentation),
  ('Trayenta Tabbleta', 'Linagliptina', '5 mg', 'tableta'::medication_presentation),
  ('Tresiba', 'Insulina', '100 U/ml', 'inyectable'::medication_presentation),
  ('Tri', 'Losartán', '100 mg', 'tableta'::medication_presentation),
  ('Triglicol', 'Rosuvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Trilipix', 'Ácido fenofíbrico', '135 mg', 'capsula'::medication_presentation),
  ('Triplixam', 'Perindopril + Indapamida + Amlodipina', '10 mg + 2.5 mg + 10 mg', 'tableta'::medication_presentation),
  ('Triplixam', 'Perindopril + Indapamida + Amlodipina', '5 mg + 1.25 mg + 10 mg', 'tableta'::medication_presentation),
  ('Triplixam', 'Perindopril + Indapamida + Amlodipina', '5 mg + 1.25 mg + 5 mg', 'tableta'::medication_presentation),
  ('Triplixan', 'Perindopril + Indapamida + Amlodipina', '10 mg + 2.5 mg + 10 mg', 'tableta'::medication_presentation),
  ('Triplixan', 'Perindopril + Indapamida + Amlodipina', '10 mg + 2.5 mg + 5 mg', 'tableta'::medication_presentation),
  ('Triplixan', 'Perindopril + Indapamida + Amlodipina', '5 mg + 1.25 mg + 10 mg', 'tableta'::medication_presentation),
  ('Triplixan', 'Perindopril + Indapamida + Amlodipina', '5 mg + 1.25 mg + 5 mg', 'tableta'::medication_presentation),
  ('Ulsen', 'Omeprazol', '20 mg', 'capsula'::medication_presentation),
  ('Unocef', 'Cefixima', '400 mg', 'capsula'::medication_presentation),
  ('Validal', 'Pantoprazol', '10 mg', 'tableta'::medication_presentation),
  ('Validal', 'Pantoprazol', '40 mg', 'tableta'::medication_presentation),
  ('Valsartán', 'Valsartán', '150 mg', 'tableta'::medication_presentation),
  ('Valsartán', 'Valsartán', '160 mg', 'tableta'::medication_presentation),
  ('Valsartán', 'Valsartán', '320 mg', 'tableta'::medication_presentation),
  ('Valsartán Amlodipina', 'Valsartán Amlodipina', '160 mg', 'tableta'::medication_presentation),
  ('Valvey', 'Insulina', '100 U/ml', 'inyectable'::medication_presentation),
  ('Varteral', 'Valsartán + Amlodipina', '160 mg + 5 mg', 'tableta'::medication_presentation),
  ('Varteral HCT', 'Valsartán + Amlodipina', '160 mg + 10 mg + 12.5 mg', 'tableta'::medication_presentation),
  ('Varteral HCT', 'Valsartán + Amlodipina', '160 mg + 5 mg + 12.5 mg', 'tableta'::medication_presentation),
  ('Vastarel', 'Trimetazidina', '35 mg', 'tableta'::medication_presentation),
  ('Vastarel LP', 'Trimetazidina', '80 mg', 'tableta'::medication_presentation),
  ('Vastarel MR', 'Trimetazidina', '35 mg', 'tableta'::medication_presentation),
  ('Vastarel MR', 'Trimetazidina', '80 mg', 'tableta'::medication_presentation),
  ('Vepidal Tomr', 'Diosmina + Hesperidina', '1000 mg', 'tableta'::medication_presentation),
  ('Verapamilo', 'Verapamilo', '240 mg', 'tableta'::medication_presentation),
  ('Vidartil', 'Vildagliptina', '50 mg', 'tableta'::medication_presentation),
  ('Vildagliptina', 'Vildagliptina', '50 mg', 'tableta'::medication_presentation),
  ('Vilzer', 'Vildagliptina', '50 mg', 'tableta'::medication_presentation),
  ('Vilzer Jalra', 'Vildagliptina', '50 mg', 'tableta'::medication_presentation),
  ('Vilzermet', 'Vildagliptina + Metformina', '50 mg', 'tableta'::medication_presentation),
  ('Vilzermet', 'Vildagliptina + Metformina', '50 mg + 1000 mg', 'tableta'::medication_presentation),
  ('Vilzermet', 'Vildagliptina + Metformina', '50 mg + 500 mg', 'tableta'::medication_presentation),
  ('Vilzermet', 'Vildagliptina + Metformina', '50 mg + 850 mg', 'tableta'::medication_presentation),
  ('Vivitar', 'Espironolactona', '100 mg', 'tableta'::medication_presentation),
  ('Vivitar', 'Espironolactona', '25 mg', 'tableta'::medication_presentation),
  ('Vymada', 'Sacubitril + Valsartán', '100 mg', 'tableta'::medication_presentation),
  ('Vymada', 'Sacubitril + Valsartán', '200 mg', 'tableta'::medication_presentation),
  ('Vymada', 'Sacubitril + Valsartán', '50 mg', 'tableta'::medication_presentation),
  ('Warfarina', 'Warfarina', '5 mg', 'tableta'::medication_presentation),
  ('Winthrop', 'Metformina', '850 mg', 'tableta'::medication_presentation),
  ('XR', 'Metformina', '1000 mg', 'tableta'::medication_presentation),
  ('XR', 'Metformina', '750 mg', 'tableta'::medication_presentation),
  ('Xigduo XR', 'Dapagliflozina + Metformina', '10 mg + 100 mg', 'tableta'::medication_presentation),
  ('Xigduo XR', 'Dapagliflozina + Metformina', '10 mg + 1000 mg', 'tableta'::medication_presentation),
  ('Xigduo XR', 'Dapagliflozina + Metformina', '5 mg + 100 mg', 'tableta'::medication_presentation),
  ('Xigduo XR', 'Dapagliflozina + Metformina', '5 mg + 1000 mg', 'tableta'::medication_presentation),
  ('Xuniro', 'Rosuvastatina', '10 mg', 'tableta'::medication_presentation),
  ('Xuniro', 'Rosuvastatina', '20 mg', 'tableta'::medication_presentation),
  ('Ácido Folico', 'Ácido Folico', '1 mg', 'tableta'::medication_presentation),
  ('Ácido Folico', 'Ácido Folico', '5 mg', 'tableta'::medication_presentation),
  ('Ácido Tranaxemico', 'Ácido Tranaxemico', '500 mg', 'tableta'::medication_presentation)
) AS x(commercial_name, active_ingredient, concentration, presentation)
WHERE NOT EXISTS (
  SELECT 1 FROM medications
  WHERE doctor_id = d.id
    AND LOWER(commercial_name) = LOWER(x.commercial_name)
    AND COALESCE(LOWER(concentration), '') = COALESCE(LOWER(x.concentration), '')
);

-- Verificación (opcional):
-- SELECT doctor_id, COUNT(*) FROM medications GROUP BY doctor_id;
-- SELECT presentation, COUNT(*) FROM medications GROUP BY presentation ORDER BY 2 DESC;
